// chat/src/pages/Layout.vue
<script setup lang="ts">
import LeftSidebar from './chat/LeftSidebar.vue';
import MessageCon from './chat/MessageCon.vue';
import SideMenu from '@/components/menu/SideMenu.vue';

</script>
<template>
  <div class="layout">
    <div class="sidebar_menu">
      <SideMenu />
    </div>
    <div class="left">
      <LeftSidebar />
    </div>
    <div class="right">
      <MessageCon />
    </div>
  </div>  
</template>
<style lang="scss" scoped>
.layout {
  display: flex;
  height: 100vh;
  .sidebar_menu {
    width: 70px;
    background-color: #316340;
    height: 100vh;
  }
  .left {
    width: 300px;
  }
  .right {
    flex: 1;
  }
}
</style>

// chat-react/src/pages/Layout.tsx

import SideMenu from '@/components/menu/SideMenu'
import LeftSideBar from '@/pages/chat/LeftSidebar'
import MessageCon from '@/pages/chat/MessageCon'
import './Layout.scss'
function Layout() {

  return(
    <div className="layout">
      <div className="sidebar_menu">
        <SideMenu />
      </div>
      <div className="left">
        <LeftSideBar />
      </div>
      <div className="right">
        <MessageCon />
      </div>
    </div>
  )
}
export default Layout
